# frozen_string_literal: true

D = Steep::Diagnostic

target :app do
  ignore 'main.rb'
  ignore 'exec'
  ignore 'src'
  check 'test'
  signature 'sig'

  library 'fileutils'

  configure_code_diagnostics(D::Ruby.default)
end

target :test do
  ignore 'main.rb'
  ignore 'exec'
  ignore 'src'
  check 'test'
  signature 'sig'

  library 'fileutils'
  library 'minitest'

  configure_code_diagnostics(D::Ruby.default)
end
